version: '3.7'

services:

  nginx:
    build: .
    network_mode: host
    command: [nginx, '-g', 'daemon off;']

    expose:
      - 80
      - 443

    volumes:
      - /home/ec2-user/website_1/staticfiles:/website_1-static/
      - /home/ec2-user/website_2/staticfiles:/website_2-static/